# Generated by Django 5.2.7 on 2025-10-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_book_options_remove_book_recipe_recipe_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.book', verbose_name='Book'),
        ),
    ]
